export const wordData = [
  {
    date: '2024-08-01',
    text: 'Das ist ein Beispieltext.',
    question: 'Was ist das Ausmaß der Schäden?',
    tip1: 'Remember to always use "das" with Ausmaß.',
    tip2: 'It often appears in the genitive case.',
    tip3: 'Pair with adjectives to describe the extent more precisely.',
    example1: 'Das Ausmaß der Schäden ist enorm.',
    example2: 'Die Regierung hat das Ausmaß der Umweltkatastrophe unterschätzt.',
    example3: 'Wir müssen das Ausmaß des Problems verstehen, bevor wir handeln.',
    example4: 'Das Ausmaß der Krise wurde erst später erkannt.',
    example5: 'Das Ausmaß der Zerstörung war weitreichend.',
    tag: 'b1',
  },
  {
    date: '2024-08-02',
    text: 'Hier ist ein weiterer Beispieltext.',
    question: 'Wie kann das Ausmaß der Schwierigkeiten beschrieben werden?',
    tip1: 'Use "das" with Ausmaß for accurate grammar.',
    tip2: 'Often used in descriptive contexts.',
    tip3: 'Combines well with qualitative adjectives.',
    example1: 'Das Ausmaß der Schwierigkeiten war größer als erwartet.',
    example2: 'Er konnte das Ausmaß der Belastungen nicht abschätzen.',
    example3: 'Die Berichte zeigen das Ausmaß der Verunsicherung.',
    example4: 'Das Ausmaß der Krise wird durch neue Daten verdeutlicht.',
    example5: 'Das Ausmaß des finanziellen Defizits ist besorgniserregend.',
    tag: 'b1',
  },
  {
    date: '2024-08-03',
    text: 'Beispieltext für eine andere Situation.',
    question: 'Welches Ausmaß haben die Veränderungen?',
    tip1: 'Keep "das" with Ausmaß in most contexts.',
    tip2: 'Commonly used in academic and formal writing.',
    tip3: 'Helps in detailing the intensity or extent of a situation.',
    example1: 'Das Ausmaß der Veränderungen ist signifikant.',
    example2: 'Wissenschaftler messen das Ausmaß des Klimawandels.',
    example3: 'Das Ausmaß der Auswirkungen wird zunehmend klarer.',
    example4: 'Die Schwere des Ausmaßes der Umstrukturierung war beachtlich.',
    example5: 'Das Ausmaß der Verbesserungen war deutlich sichtbar.',
    tag: 'b1',
  },
  {
    date: '2024-08-04',
    text: 'Ein weiteres Beispiel für die Anwendung.',
    question: 'Wie beschreibt man das Ausmaß der Anstrengungen?',
    tip1: 'Always pair "das" with Ausmaß for correct usage.',
    tip2: 'Often follows verbs of assessment or description.',
    tip3: 'Useful in detailed and explanatory contexts.',
    example1: 'Das Ausmaß der Anstrengungen war überwältigend.',
    example2: 'Die Anstrengungen zum Umweltschutz zeigten ein bemerkenswertes Ausmaß.',
    example3: 'Das Ausmaß der Bemühungen war unerhört hoch.',
    example4: 'Das tatsächliche Ausmaß der Arbeit wird oft unterschätzt.',
    example5: 'Das Ausmaß der Unterstützung übertraf alle Erwartungen.',
    tag: 'b1',
  },
];
