

  {
    date: 'June 27, 2024',
    wordNo: '270624',
    article: '',
    word: '',
    grammar: '',
    image: 'https://raw.githubusercontent.com/ayhanmetin/wordimage/main/1/.png',
    example1:'',
    example2: '',
    example3: '',
    example4: '',
    example5: '',
    meaningENG: '',
    meaningTR: '',
    tip1: '',
    tip2: '',
    tip3: '',
    tag: 'basics',
  },
