const wordData = [
  {
    date: 'April 17, 2024',
    word: 'Verhandlung',
    example1: 'Die Verhandlung war lang und anstrengend.',
    example2: '',
    meaningENG: 'negotiation',
    meaningTR: 'müzakere',
    id: '1',
    level: "1",
    block: "1",
    grammar: "noun",
  },
  {
    date: '2023-04-18',
    word: 'entwickeln',
    example1: 'Wir entwickeln eine neue Software.',
    example2: '',
    meaningENG: 'to develop',
    meaningTR: 'geliştirmek',
    id: '2',
    level: "1",
    block: "1",
    grammar: "noun",
  },
  {
    date: '2023-04-18',
    word: 'entwickeln',
    example1: 'Wir entwickeln eine neue Software.',
    example2: '',
    meaningENG: 'to develop',
    meaningTR: 'geliştirmek',
    id: '2',
    level: "1",
    block: "1",
    grammar: "noun",
  },
  {
    date: '2023-04-18',
    word: 'entwickeln',
    example1: 'Wir entwickeln eine neue Software.',
    example2: '',
    meaningENG: 'to develop',
    meaningTR: 'geliştirmek',
    id: '2',
    level: "1",
    block: "1",
    grammar: "noun",
  },
  {
    date: '2023-04-18',
    word: 'entwickeln',
    example1: 'Wir entwickeln eine neue Software.',
    example2: '',
    meaningENG: 'to develop',
    meaningTR: 'geliştirmek',
    id: '2',
    level: "1",
    block: "1",
    grammar: "noun",
  },
  {
    date: '2023-04-18',
    word: 'entwickeln',
    example1: 'Wir entwickeln eine neue Software.',
    example2: '',
    meaningENG: 'to develop',
    meaningTR: 'geliştirmek',
    id: '2',
    level: "1",
    block: "1",
    grammar: "noun",
  },

];

export default wordData;
