{
  date: 'June 27, 2024',
  wordNo: '230724',
  plural: '',
  Präteritum: '',
  PartizipII: '',
  article: '',
  word: '',
  grammar: '',
  image: 'https://raw.githubusercontent.com/ayhanmetin/wordimage/main/1/.png',
  example1: '',
  example2: '',
  example3: '',
  example4: '',
  example5: '',
  meaningENG: '',
  meaningTR: '',
  tip1: '',
  tip2: '',
  tip3: '',
  tag: 'basics',
},