const wordData = [
  {
    date: 'April 18, 2024',
    word: 'Verhandlung',
    grammar: 'noun',
    image:
      'https://raw.githubusercontent.com/ayhanmetin/wordimage/main/1/beenden.png',
    example1: 'Die Verhandlung war lang und anstrengend.',
    example2: 'Die Parteien erreichten schließlich eine Verhandlung.',
    means: 'The act of negotiating or bargaining.',
    meaningENG: 'negotiation',
    meaningTR: 'müzakere',
    id: '1',
    tip: '',
    tag: 'basics',
    grammar2: 'Noun, feminine',
  },
  {
    date: 'April 19, 2024',
    word: 'Zulassung',
    grammar: 'noun',
    image:
      'https://raw.githubusercontent.com/ayhanmetin/wordimage/main/2/zulassung.png',
    example1: 'Die Zulassung für das Programm war sehr kompetitiv.',
    example2: 'Ohne Zulassung dürfen Sie das Gebäude nicht betreten.',
    means: 'The act of permitting or authorizing.',
    meaningENG: 'admission',
    meaningTR: 'kabul',
    id: '2',
    tip: '',
    tag: 'basics',
    grammar2: 'Noun, feminine',
  },
  {
    date: 'April 26, 2024',
    word: 'Anspruch',
    grammar: 'noun',
    image:
      'https://raw.githubusercontent.com/ayhanmetin/wordimage/main/9/anspruch.png',
    example1: 'Er erhob Anspruch auf das Erbe.',
    example2: 'Die Qualität des Produkts erfüllt unseren Anspruch.',
    means: 'A right or claim to something.',
    meaningENG: 'claim',
    meaningTR: 'talep',
    id: '91',
    tip: '',
    tag: 'basics',
    grammar2: 'Noun, masculine',
  },
  {
    date: 'April 20, 2024',
    word: 'Entwicklung',
    grammar: 'noun',
    image:
      'https://raw.githubusercontent.com/ayhanmetin/wordimage/main/3/entwicklung.png',
    example1: 'Die Entwicklung neuer Technologien ist atemberaubend.',
    example2: 'Dieses Land braucht eine nachhaltige Entwicklung.',
    means: 'The process of developing or being developed.',
    meaningENG: 'development',
    meaningTR: 'gelişim',
    id: '3',
    tip: '',
    tag: 'basics',
    grammar2: 'Noun, feminine',
  },
  {
    date: 'April 21, 2024',
    word: 'Freiheit',
    grammar: 'noun',
    image:
      'https://raw.githubusercontent.com/ayhanmetin/wordimage/main/4/freiheit.png',
    example1: 'Die Freiheit der Kunst ist ein wichtiges Gut.',
    example2: 'Er kämpfte sein Leben lang für Freiheit.',
    means: 'The power or right to act, speak, or think as one wants.',
    meaningENG: 'freedom',
    meaningTR: 'özgürlük',
    id: '4',
    tip: '',
    tag: 'basics',
    grammar2: 'Noun, feminine',
  },
  {
    date: 'April 22, 2024',
    word: 'Gleichgewicht',
    grammar: 'noun',
    image:
      'https://raw.githubusercontent.com/ayhanmetin/wordimage/main/5/gleichgewicht.png',
    example1: 'Das ökologische Gleichgewicht ist sehr empfindlich.',
    example2: 'Er verlor das Gleichgewicht und fiel.',
    means: 'The state of being in balance or equilibrium.',
    meaningENG: 'balance',
    meaningTR: 'denge',
    id: '5',
    tip: '',
    tag: 'basics',
    grammar2: 'Noun, neuter',
  },
  {
    date: 'April 23, 2024',
    word: 'Kraft',
    grammar: 'noun',
    image:
      'https://raw.githubusercontent.com/ayhanmetin/wordimage/main/6/kraft.png',
    example1: 'Die Kraft des Wassers ist nicht zu unterschätzen.',
    example2: 'Mit aller Kraft stemmte er sich gegen die Tür.',
    means:
      'The strength or energy as an attribute of physical action or movement.',
    meaningENG: 'force',
    meaningTR: 'kuvvet',
    id: '6',
    tip: '',
    tag: 'basics',
    grammar2: 'Noun, feminine',
  },
  {
    date: 'April 24, 2024',
    word: 'Beziehung',
    grammar: 'noun',
    image:
      'https://raw.githubusercontent.com/ayhanmetin/wordimage/main/7/beziehung.png',
    example1: 'Sie hatten eine lange, komplizierte Beziehung.',
    example2: 'Die Beziehung zwischen den beiden Ländern verbessert sich.',
    means:
      'The way in which two or more concepts, objects, or people are connected.',
    meaningENG: 'relationship',
    meaningTR: 'ilişki',
    id: '7',
    tip: '',
    tag: 'basics',
    grammar2: 'Noun, feminine',
  },
  {
    date: 'April 25, 2024',
    word: 'Berechtigung',
    grammar: 'noun',
    image:
      'https://raw.githubusercontent.com/ayhanmetin/wordimage/main/8/berechtigung.png',
    example1: 'Er hatte keine Berechtigung, die Dateien zu ändern.',
    example2: 'Die Berechtigung zum Zugriff auf das System wurde erteilt.',
    means: 'The authority or permission to do something.',
    meaningENG: 'authorization',
    meaningTR: 'yetki',
    id: '8',
    tip: '',
    tag: 'basics',
    grammar2: 'Noun, feminine',
  },
  {
    date: 'April 26, 2024',
    word: 'Anspruch',
    grammar: 'noun',
    image:
      'https://raw.githubusercontent.com/ayhanmetin/wordimage/main/9/anspruch.png',
    example1: 'Er erhob Anspruch auf das Erbe.',
    example2: 'Die Qualität des Produkts erfüllt unseren Anspruch.',
    means: 'A right or claim to something.',
    meaningENG: 'claim',
    meaningTR: 'talep',
    id: '9',
    tip: '',
    tag: 'basics',
    grammar2: 'Noun, masculine',
  },
  {
    date: 'April 27, 2024',
    word: 'Einsicht',
    grammar: 'noun',
    image:
      'https://raw.githubusercontent.com/ayhanmetin/wordimage/main/10/einsicht.png',
    example1: 'Durch die Dokumente gewannen wir Einsicht in die Lage.',
    example2: 'Sie zeigte große Einsicht in ihren Fehlern.',
    means: 'An understanding or insight into something.',
    meaningENG: 'insight',
    meaningTR: 'anlayış',
    id: '10',
    tip: '',
    tag: 'basics',
    grammar2: 'Noun, feminine',
  },
  {
    date: 'April 28, 2024',
    word: 'Verpflichtung',
    grammar: 'noun',
    image:
      'https://raw.githubusercontent.com/ayhanmetin/wordimage/main/11/verpflichtung.png',
    example1: 'Sie fühlte eine tiefe Verpflichtung, zu helfen.',
    example2: 'Die Verpflichtung wurde offiziell im Vertrag festgehalten.',
    means: 'An obligation or duty to do something.',
    meaningENG: 'obligation',
    meaningTR: 'yükümlülük',
    id: '11',
    tip: '',
    tag: 'basics',
    grammar2: 'Noun, feminine',
  },
  {
    date: 'April 29, 2024',
    word: 'Erfolg',
    grammar: 'noun',
    image:
      'https://raw.githubusercontent.com/ayhanmetin/wordimage/main/12/erfolg.png',
    example1: 'Der Erfolg des Projekts war unsicher.',
    example2: 'Sie feierten den großen Erfolg ihrer Mannschaft.',
    means: 'The achievement of an aim or goal.',
    meaningENG: 'success',
    meaningTR: 'başarı',
    id: '12',
    tip: '',
    tag: 'basics',
    grammar2: 'Noun, masculine',
  },
  {
    date: 'April 30, 2024',
    word: 'Wandel',
    grammar: 'noun',
    image:
      'https://raw.githubusercontent.com/ayhanmetin/wordimage/main/13/wandel.png',
    example1: 'Der technologische Wandel verändert die Arbeitswelt.',
    example2: 'Sie suchte nach einem Wandel in ihrem Leben.',
    means: 'Change or transformation.',
    meaningENG: 'change',
    meaningTR: 'değişim',
    id: '13',
    tip: '',
    tag: 'basics',
    grammar2: 'Noun, masculine',
  },
  {
    date: 'May 1, 2024',
    word: 'Risiko',
    grammar: 'noun',
    image:
      'https://raw.githubusercontent.com/ayhanmetin/wordimage/main/14/risiko.png',
    example1: 'Das Risiko war zu groß, um es zu ignorieren.',
    example2: 'Sie nahm das Risiko auf sich und investierte.',
    means: 'A situation involving exposure to danger or loss.',
    meaningENG: 'risk',
    meaningTR: 'risk',
    id: '14',
    tip: '',
    tag: 'basics',
    grammar2: 'Noun, neuter',
  },
  {
    date: 'May 2, 2024',
    word: 'Gerechtigkeit',
    grammar: 'noun',
    image:
      'https://raw.githubusercontent.com/ayhanmetin/wordimage/main/15/gerechtigkeit.png',
    example1: 'Sie kämpfte ihr ganzes Leben für Gerechtigkeit.',
    example2: 'Gerechtigkeit muss für alle gleich sein.',
    means: 'The quality of being fair and reasonable.',
    meaningENG: 'justice',
    meaningTR: 'adalet',
    id: '15',
    tip: '',
    tag: 'basics',
    grammar2: 'Noun, feminine',
  },
  {
    date: 'May 3, 2024',
    word: 'Leistung',
    grammar: 'noun',
    image:
      'https://raw.githubusercontent.com/ayhanmetin/wordimage/main/16/leistung.png',
    example1: 'Ihre Leistung in der Schule verbesserte sich.',
    example2: 'Die Maschine erbringt eine beeindruckende Leistung.',
    means: 'The action of accomplishing or achieving something.',
    meaningENG: 'performance',
    meaningTR: 'performans',
    id: '16',
    tip: '',
    tag: 'basics',
    grammar2: 'Noun, feminine',
  },
  {
    date: 'May 4, 2024',
    word: 'Herausforderung',
    grammar: 'noun',
    image:
      'https://raw.githubusercontent.com/ayhanmetin/wordimage/main/17/herausforderung.png',
    example1: 'Das neue Projekt stellte eine große Herausforderung dar.',
    example2: 'Sie nahm jede Herausforderung an, die ihr Leben bot.',
    means: 'A call to prove or justify something.',
    meaningENG: 'challenge',
    meaningTR: 'meydan okuma',
    id: '17',
    tip: '',
    tag: 'basics',
    grammar2: 'Noun, feminine',
  },
  {
    date: 'May 5, 2024',
    word: 'Perspektive',
    grammar: 'noun',
    image:
      'https://raw.githubusercontent.com/ayhanmetin/wordimage/main/18/perspektive.png',
    example1: 'Die Perspektive auf das Problem veränderte sich.',
    example2: 'Von hier aus hat man eine wunderbare Perspektive.',
    means: 'A particular attitude towards or way of regarding something.',
    meaningENG: 'perspective',
    meaningTR: 'perspektif',
    id: '18',
    tip: '',
    tag: 'living',
    grammar2: 'Noun, feminine',
  },
  {
    date: 'May 6, 2024',
    word: 'Engagement',
    grammar: 'noun',
    image:
      'https://raw.githubusercontent.com/ayhanmetin/wordimage/main/19/engagement.png',
    example1: 'Ihr Engagement für die Sache war inspirierend.',
    example2: 'Das Unternehmen fördert das Engagement seiner Mitarbeiter.',
    means: 'The fact of being involved in or committed to something.',
    meaningENG: 'commitment',
    meaningTR: 'bağlılık',
    id: '19',
    tip: '',
    tag: 'basics',
    grammar2: 'Noun, neuter',
  },
  {
    date: 'May 7, 2024',
    word: 'Integrität',
    grammar: 'noun',
    image:
      'https://raw.githubusercontent.com/ayhanmetin/wordimage/main/20/integrität.png',
    example1: 'Er war bekannt für seine Integrität und Ehrlichkeit.',
    example2: 'Die Integrität des Systems muss gewährleistet sein.',
    means: 'The quality of being honest and having strong moral principles.',
    meaningENG: 'integrity',
    meaningTR: 'dürüstlük',
    id: '20',
    tip: '',
    tag: 'basics',
    grammar2: 'Noun, feminine',
  },
  {
    date: 'April 26, 2024',
    word: 'Zurechnungsfähigkeit',
    grammar: 'noun',
    image:
      'https://raw.githubusercontent.com/ayhanmetin/wordimage/main/20/zurechnungsfähigkeit.png',
    example1: 'Der Angeklagte wurde auf seine Zurechnungsfähigkeit untersucht.',
    example2: 'Zurechnungsfähigkeit spielt eine wichtige Rolle im Strafrecht.',
    means: 'The capability of being legally responsible for ones actions.',
    meaningENG: 'sanity',
    meaningTR: 'akıl sağlığı',
    id: '21',
    tip: '',
    tag: 'basics',
    grammar2: 'Noun, feminine',
  },
  {
    date: 'April 26, 2024',
    word: 'Souveränität',
    grammar: 'noun',
    image:
      'https://raw.githubusercontent.com/ayhanmetin/wordimage/main/21/souveränität.png',
    example1: 'Die Souveränität des Staates ist unantastbar.',
    example2: 'Die Frage der Souveränität ist in diesen Verhandlungen zentral.',
    means: 'The supreme authority within a territory.',
    meaningENG: 'sovereignty',
    meaningTR: 'egemenlik',
    id: '22',
    tip: '',
    tag: 'basics',
    grammar2: 'Noun, feminine',
  },
  {
    date: 'April 26, 2024',
    word: 'Determinismus',
    grammar: 'noun',
    image:
      'https://raw.githubusercontent.com/ayhanmetin/wordimage/main/22/determinismus.png',
    example1:
      'Der Determinismus behauptet, dass alle Ereignisse vorbestimmt sind.',
    example2:
      'Die Debatte über Freiheit und Determinismus ist jahrhundertealt.',
    means:
      'The philosophical doctrine that all events are determined completely by previously existing causes.',
    meaningENG: 'determinism',
    meaningTR: 'determinizm',
    id: '23',
    tip: '',
    tag: 'basics',
    grammar2: 'Noun, masculine',
  },
  {
    date: 'April 26, 2024',
    word: 'Konvergenz',
    grammar: 'noun',
    image:
      'https://raw.githubusercontent.com/ayhanmetin/wordimage/main/23/konvergenz.png',
    example1:
      'Die Konvergenz von Technologie und Medien verändert die Industrie.',
    example2:
      'Wirtschaftswissenschaftler studieren die Konvergenz zwischen den Ländern.',
    means: 'The process or state of converging.',
    meaningENG: 'convergence',
    meaningTR: 'yakınsama',
    id: '24',
    tip: '',
    tag: 'basics',
    grammar2: 'Noun, feminine',
  },
  {
    date: 'April 26, 2024',
    word: 'Ambivalenz',
    grammar: 'noun',
    image:
      'https://raw.githubusercontent.com/ayhanmetin/wordimage/main/24/ambivalenz.png',
    example1: 'Sie empfand eine tiefe Ambivalenz gegenüber seiner Rückkehr.',
    example2: 'Ambivalenz in seinen Gefühlen machte die Entscheidung schwer.',
    means:
      'The state of having basicsed feelings or contradictory ideas about something or someone.',
    meaningENG: 'ambivalence',
    meaningTR: 'ikirciklilik',
    id: '25',
    tip: '',
    tag: 'basics',
    grammar2: 'Noun, feminine',
  },
];

export default wordData;
